spring:
    devtools:
        livereload:
            enabled: : true

    datasource:
        hikari:
            maximum-pool-size: 4
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/dabaseName?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
        username: mariadb_user_account
        password: 1234