spring:
    config:
        activate:
            on-profile: prod
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        check-template-location: true
        cache: false
server:
    port: 8080
    servlet:
        context-path: /spring-boot
        session:
            timeout: 600s
    tomcat:
        uri-encoding: UTF-8
        threads:
            min-spare: 20
            max: 200
